### ISSUE TITLE
  chrome.storage.local.set({key: value}, function() SET to chrome.storage.sync.set({key: value}, function() {

### ISSUE THREAD

**Issue by KevsBitcoin** [maripo/CustomFilter#146]
Can we please add this in the current update ?
https://developer.chrome.com/extensions/storage

    chrome.storage.sync.set({key: value}, function() {
      console.log('Value is set to ' + value);
    });
  
    chrome.storage.sync.get(['key'], function(result) {
      console.log('Value currently is ' + result.key);
    });
or storage.local:

    chrome.storage.local.set({key: value}, function() {
      console.log('Value is set to ' + value);
    });
  
    chrome.storage.local.get(['key'], function(result) {
      console.log('Value currently is ' + result.key);
    });
Found here
https://developer.chrome.com/extensions/storage    chrome.storage.sync.set({key: value}, function() {
      console.log('Value is set to ' + value);
    });
  
    chrome.storage.sync.get(['key'], function(result) {
      console.log('Value currently is ' + result.key);
    });
or storage.local:

    chrome.storage.local.set({key: value}, function() {
      console.log('Value is set to ' + value);
    });
  
    chrome.storage.local.get(['key'], function(result) {
      console.log('Value currently is ' + result.key);
    });
Found here
https://developer.chrome.com/extensions/storage

**Comment by maripo** [comment]
Thanks. Remote sync feature was added!
