### ISSUE TITLE
Why does it use analytics?

### ISSUE THREAD

**Issue by SuperJayRay** [maripo/CustomFilter#152]
The code includes a analytics file in src code. Just wondering why this app is using google analytics as a backdoor to track users' browsing history. Seems very unnecessary?

**Comment by maripo** [comment]
We collect anonymous statistical information to improve the user experience and to determine which features to enhance.
Analytics does not have the ability to obtain or submit any personal information about users.

**Comment by SuperJayRay** [comment]
Hello! One really quick question: is it possible to opt out of the analytics please?

**Comment by swaree** [comment]
Bump. Completely unnecessary and no disclaimer whatsoever. Uninstalling it right now.
